// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIb07SnzF4FVp6aY-RejR8Ug4X_VjAfpw',
    appId: '1:824519642335:web:99fab4b7946b265555ed6a',
    messagingSenderId: '824519642335',
    projectId: 'fixit-74c45',
    authDomain: 'fixit-74c45.firebaseapp.com',
    storageBucket: 'fixit-74c45.firebasestorage.app',
    measurementId: 'G-ZRFZJPCYGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUiCauTg57hII21vjlmobUqEuruzugZ_I',
    appId: '1:824519642335:android:ba1d04061cdd40ca55ed6a',
    messagingSenderId: '824519642335',
    projectId: 'fixit-74c45',
    storageBucket: 'fixit-74c45.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDulIAiBvX5plk-uYcJnz-ZbxcZqctnj8Q',
    appId: '1:824519642335:ios:346d0b3a2bb1eff155ed6a',
    messagingSenderId: '824519642335',
    projectId: 'fixit-74c45',
    storageBucket: 'fixit-74c45.firebasestorage.app',
    iosClientId: '824519642335-1ubo5jbifs53jebv4ddpn06dqkg03cgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixitGh',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDulIAiBvX5plk-uYcJnz-ZbxcZqctnj8Q',
    appId: '1:824519642335:ios:346d0b3a2bb1eff155ed6a',
    messagingSenderId: '824519642335',
    projectId: 'fixit-74c45',
    storageBucket: 'fixit-74c45.firebasestorage.app',
    iosClientId: '824519642335-1ubo5jbifs53jebv4ddpn06dqkg03cgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixitGh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIb07SnzF4FVp6aY-RejR8Ug4X_VjAfpw',
    appId: '1:824519642335:web:9bc9fccde31d1d9555ed6a',
    messagingSenderId: '824519642335',
    projectId: 'fixit-74c45',
    authDomain: 'fixit-74c45.firebaseapp.com',
    storageBucket: 'fixit-74c45.firebasestorage.app',
    measurementId: 'G-5W6NS5LG5Y',
  );
}
