// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMS8EfKEwtR_ZIFO4Zys-3bMDAYbdl8fo',
    appId: '1:128712950329:web:608815345cd6125a5803e8',
    messagingSenderId: '128712950329',
    projectId: 'fixit-gh-app',
    authDomain: 'fixit-gh-app.firebaseapp.com',
    storageBucket: 'fixit-gh-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZHtzQsgKdMeMFROnOSo-TQ2oefrqpkLc',
    appId: '1:128712950329:android:f5cb817d9549c8ba5803e8',
    messagingSenderId: '128712950329',
    projectId: 'fixit-gh-app',
    storageBucket: 'fixit-gh-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIhgvXci2D68XTqc47vc9FNX3zsAHmrqc',
    appId: '1:128712950329:ios:4e1511ef100840575803e8',
    messagingSenderId: '128712950329',
    projectId: 'fixit-gh-app',
    storageBucket: 'fixit-gh-app.firebasestorage.app',
    iosBundleId: 'com.example.fixitGh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIhgvXci2D68XTqc47vc9FNX3zsAHmrqc',
    appId: '1:128712950329:ios:4e1511ef100840575803e8',
    messagingSenderId: '128712950329',
    projectId: 'fixit-gh-app',
    storageBucket: 'fixit-gh-app.firebasestorage.app',
    iosBundleId: 'com.example.fixitGh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMS8EfKEwtR_ZIFO4Zys-3bMDAYbdl8fo',
    appId: '1:128712950329:web:7cf32b7522c2395f5803e8',
    messagingSenderId: '128712950329',
    projectId: 'fixit-gh-app',
    authDomain: 'fixit-gh-app.firebaseapp.com',
    storageBucket: 'fixit-gh-app.firebasestorage.app',
  );
}
